# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_note_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='create_date',
            field=models.DateTimeField(auto_created=True, blank=True, verbose_name='Дата создания'),
        ),
    ]
