# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-10 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180811_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='create_date',
        ),
    ]
